codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        # Require 1% coverage, i.e., always succeed
        target: 1%
        flags:
          - unittests
        paths:
          - "!gedidb/tests/"
      unittests:
        target: 90%
        flags:
          - unittests
        paths:
          - "!icesat2db/tests/"
      mypy:
        target: 20%
        flags:
          - mypy
    patch: false
    changes: false

comment: false

flags:
  unittests:
    paths:
      - "icesat2db"
      - "!icesat2db/tests"
    carryforward: false
  mypy:
    paths:
      - "icesat2db"
    carryforward: false